language: python
python:
  - "2.7"
install:
  - pip install xml2rfc
script:
  - xml2rfc I-D-Profile-Negotiation.xml
  - xml2rfc I-D-Profile-Negotiation.xml --html
after_success:
  - ./.travis_build_pages
cache:
  - pip
